# Generated by Django 4.1.3 on 2022-11-24 08:33

from django.db import migrations, models
import django.db.models.deletion
import scraper.models._sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('custom_url', models.CharField(blank=True, max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('subscriber', models.CharField(max_length=8, null=True, validators=[scraper.models._sql.validate_human_readable_number])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Channel',
                'unique_together': {('channel_id', 'custom_url')},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=128, unique=True)),
                ('length', models.DurationField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('view_count', models.CharField(max_length=8, null=True, validators=[scraper.models._sql.validate_human_readable_number])),
                ('like_count', models.CharField(max_length=8, null=True, validators=[scraper.models._sql.validate_human_readable_number])),
                ('comment_count', models.CharField(max_length=8, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scraper.channel')),
            ],
            options={
                'verbose_name': 'Video',
                'ordering': ('channel', '-published_at', '-view_count', '-like_count', '-comment_count'),
            },
        ),
        migrations.CreateModel(
            name='VideoMongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mv_description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('m_video', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_mongo_video', to='scraper.video')),
            ],
            options={
                'verbose_name': 'Video OnMongoDB',
            },
        ),
        migrations.CreateModel(
            name='ChannelMongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('m_channel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_mongo_channel', to='scraper.channel')),
            ],
            options={
                'verbose_name': 'About Channel',
            },
        ),
    ]
