# Generated by Django 4.1.3 on 2022-11-24 08:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, validators=[core.models.validate_upper_case])),
                ('value', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Settings',
                'ordering': ('key',),
            },
        ),
    ]
